version: '3.8'

services:
  hbase:
    build:
      dockerfile: DockerfileHbase
    env_file:
      - ../resources/environment/hbase.env
    restart: unless-stopped
    ports:
      - 16010:16010
      - 9870:9870
      - 9000:9000
      - 7077:7077
      - 4040:4040
      - 8088:8088
      - 8020:8020
      - 2181:2181
      - 22:22
    deploy:
      resources:
        limits:
          cpus: '3'  
          memory: 4G  
        reservations:
          cpus: '3'
          memory: 4G

  python_app:
    build: 
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/home/vscode/.gitconfig
      - ~/.ssh:/home/vscode/.ssh
    command: sleep infinity
  postgres:
    image: postgres
    restart: unless-stopped
    env_file: ../resources/environment/postgresql.env
    ports:
      - 5432-5442:5432
    deploy:
      resources:
        limits:
          cpus: '3'  
          memory: 4G  
        reservations:
          cpus: '3'
          memory: 4G 

networks:
  default:
    name: app-hbase
    driver: bridge
    ipam:
      driver: default